const serverErrors = {
    UNEXPECTED_SERVER_ERROR: "0",
    REQUEST_LIMIT_ERROR: "1",
    SHORT_VIDEO_ERROR: "2",
    INCORRECT_VIDEO_LINK_ERROR: "3",
    INCORRECT_VIDEO_PARAMETERS_ERROR_BAD_START_TIME: "4.1",
    INCORRECT_VIDEO_PARAMETERS_ERROR_BAD_END_TIME: "4.2",
    INCORRECT_VIDEO_PARAMETERS_ERROR_BAD_DURATION: "4.3",
    YOUTUBE_API_ERROR: "5",
    RECOGNITION_FAILED_ERROR: "6",
}
export default serverErrors
